### ISSUE TITLE
allow PRs on magento-cloud projects to be tested with MDM

### ISSUE THREAD

**Issue by keithbentrup** [PMET-public/mdm#17]
for example, https://github.com/PMET-public/magento-cloud/runs/1087043611?check_suite_focus=true

``` yml
on:
  pull_request:
    branches:
      - master
      - pmet-2.4.*
```

issues: collaborator (even if member of org but read only access) will not have access to secrets
so how to provide COMPOSER_AUTH?

also when trying to dockerize which needs repo and ref, is the right ref used?
